### PR TITLE
Resolve deadlock issue on async experiments when caller uses sync ove…

### PR DESCRIPTION
**Pull request by zizhong-zhang**
…r async

### CODE REVIEW

**Comment by zizhong-zhang** [comment]
We have some legacy mvc (netframework 4.6.1) which has lots of synchronous code.
We've found that when caller gets the Task.Result synchronously from Scientist.SicenceAsync<T>, context thread is blocked forever.

**Comment by zizhong-zhang** [comment]
thank you for the instant response on this. this is truly amazing!
would you be okay to merge this in?

**Comment by zizhong-zhang** [comment]
hi @paulbreen , thanks for help merging the PR in.
it would be fantastic if a new nuget release can be out so we will be able to consume it.

At the moment, we've forked your repo and publish a nuget from there however we know the best way to go long-term is to stick with the upstream.

Hope it does not take much effort for you to bump the version (e.g. 2.0.1)

Many thanks!

**Comment by kmc059000** [comment]
We ran into a similar issue and in researching, we found that this PR had been merged almost a year ago, with no corresponding nuget package release. Would it be possible to deploy a new nuget package for this?

**Pull request merged**
